import React from "react";
import { 
  FaExclamationTriangle as ErrorHexaIcon, 
  FaExclamationCircle as AlertHexaIcon, 
  FaEllipsisH as MoreDotIcon, 
  FaDownload as DownloadIcon, 
  FaFileAlt as FileIcon, 
  FaTh as GridIcon, 
  FaMusic as AudioIcon, 
  FaVideo as VideoIcon, 
  FaBolt as BoltIcon, 
  FaPlus as PlusIcon, 
  FaBox as BoxIcon, 
  FaTimes as CloseIcon, 
  FaCheckCircle as CheckCircleIcon, 
  FaExclamationCircle as AlertIcon, 
  FaInfoCircle as InfoIcon, 
  FaInfoCircle as ErrorIcon, 
  FaArrowUp as ArrowUpIcon, 
  FaFolder as FolderIcon, 
  FaArrowDown as ArrowDownIcon, 
  FaArrowRight as ArrowRightIcon, 
  FaUsers as GroupIcon, 
  FaBox as BoxIconLine, 
  FaStar as ShootingStarIcon, 
  FaDollarSign as DollarLineIcon, 
  FaTrash as TrashBinIcon, 
  FaChevronUp as AngleUpIcon, 
  FaChevronDown as AngleDownIcon, 
  FaPencilAlt as PencilIcon, 
  FaCheck as CheckLineIcon, 
  FaTimes as CloseLineIcon, 
  FaChevronDown as ChevronDownIcon, 
  FaPaperPlane as PaperPlaneIcon, 
  FaEnvelope as EnvelopeIcon, 
  FaLock as LockIcon, 
  FaUserAlt as UserIcon, 
  FaCalendarAlt as CalenderIcon, 
  FaEye as EyeIcon, 
  FaEyeSlash as EyeCloseIcon, 
  FaClock as TimeIcon, 
  FaCopy as CopyIcon, 
  FaChevronLeft as ChevronLeftIcon, 
  FaUserCircle as UserCircleIcon, 
  FaTasks as TaskIcon, 
  FaList as ListIcon, 
  FaTable as TableIcon, 
  FaFile as PageIcon, 
  FaChartPie as PieChartIcon, 
  FaCube as BoxCubeIcon, 
  FaPlug as PlugInIcon, 
  FaFileAlt as DocsIcon, 
  FaMailBulk as MailIcon, 
  FaEllipsisH as HorizontaLDots, 
  FaChevronUp as ChevronUpIcon, 
  FaCommentDots as ChatIcon 
} from 'react-icons/fa'; // Font Awesome Icons

export {
  ErrorHexaIcon,
  AlertHexaIcon,
  MoreDotIcon,
  DownloadIcon,
  FileIcon,
  GridIcon,
  AudioIcon,
  VideoIcon,
  BoltIcon,
  PlusIcon,
  BoxIcon,
  CloseIcon,
  CheckCircleIcon,
  AlertIcon,
  InfoIcon,
  ErrorIcon,
  ArrowUpIcon,
  FolderIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  GroupIcon,
  BoxIconLine,
  ShootingStarIcon,
  DollarLineIcon,
  TrashBinIcon,
  AngleUpIcon,
  AngleDownIcon,
  PencilIcon,
  CheckLineIcon,
  CloseLineIcon,
  ChevronDownIcon,
  PaperPlaneIcon,
  EnvelopeIcon,
  LockIcon,
  UserIcon,
  CalenderIcon,
  EyeIcon,
  EyeCloseIcon,
  TimeIcon,
  CopyIcon,
  ChevronLeftIcon,
  UserCircleIcon,
  TaskIcon,
  ListIcon,
  TableIcon,
  PageIcon,
  PieChartIcon,
  BoxCubeIcon,
  PlugInIcon,
  DocsIcon,
  MailIcon,
  HorizontaLDots,
  ChevronUpIcon,
  ChatIcon,
};
